name: Evaluate Splunk App Publication Readiness

on:
  push:
    branches:
      - 'test-readiness-pipeline'

  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, reopened, synchronize]

# Allow only 1 concurrent execution
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-workflow:
    uses: splunk-platform-apps/.github/.github/workflows/reusable-readiness-assessment.yml@dvr-123-add-check-on-navigation
    with:
      repo_name: ${{ github.event.repository.name }}
